package:
  name: icu
  version: 53.1

source:
  fn: icu4c-53_1-src.tgz
  url: http://download.icu-project.org/files/icu4c/53.1/icu4c-53_1-src.tgz
  md5: b73baa6fbdfef197608d1f69300919b9

build:
  number: 0

about:
  home: http://site.icu-project.org/home
  license: ICU
  summary: ICU is a mature, widely used set of C/C++ and Java libraries providing Unicode and Globalization support for software applications. 
