package:
  name: rios
  version: 1.3.1

source:
  fn: rios-1.3.1.tar.gz
  url: https://bitbucket.org/chchrsc/rios/downloads/rios-1.3.0.tar.gz

requirements:
  build:
    - python
    - numpy
    - scipy
    - gdal
  run:
    - python
    - numpy
    - scipy
    - gdal

about:
  home: https://bitbucket.org/chchrsc/rios/
  license: GPLv3
  summary: Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.
