package:
  name: h5py
  version: "2.3.1"

source:
  fn:  h5py-2.3.1.tar.gz
  url: https://pypi.python.org/packages/source/h/h5py/h5py-2.3.1.tar.gz
  md5: 8f32f96d653e904d20f9f910c6d9dd91

requirements:
  build:
    - python
    - numpy
    - hdf5 1.8.13
  run:
    - python
    - numpy
    - hdf5 1.8.13

test:
    imports:
        - h5py

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
  summary: The h5py package is a Pythonic interface to the HDF5 binary data format. 
