package:
  name: spd3dpointsviewer
  version: "2.2.1"

build:
  number: 1

source:
  hg_url: https://bitbucket.org/petebunting/spd-3d-points-viewer

requirements:
  build:
    - cmake
    - qt
    - hdf5 1.8.13
    - boost 1.54.0
    - gdal 1.11.1
    - spdlib 3.1.3
  run:
    - qt
    - hdf5 1.8.13
    - boost 1.54.0
    - gdal 1.11.1
    - spdlib 3.1.3

about:
  home: https://bitbucket.org/petebunting/spd-3d-points-viewer/
  license: GPLv3
  summary: SPD 3D Points Viewer is a viewer for visualising point cloud data in SPD format.
