package:
  name: sixs
  version: "1.1.1"

source:
  hg_url: https://bitbucket.org/petebunting/6s

requirements:
  build:
    - cmake
  run:

test:
  files:
  - Example_In_1.txt

about:
  home: https://bitbucket.org/petebunting/6s
  summary:  The 6S code is a basic RT code used for calculation of lookup tables in the MODIS atmospheric correction algorithm. It enables accurate simulations of satellite and plane observation, accounting for elevated targets, use of anisotropic and lambertian surfaces and calculation of gaseous absorption.  
