
package:
    name: boost
    version: "1.54.0"

source:
    fn: boost_1_54_0.tar.bz2
    url: http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2

build:
    number: 1

requirements:
    build:
     - python
     - bzip2
    run:
     - python
test:
    imports:

about:
    home: http://www.boost.org/
    license: Boost-1.0

