package:
  name: gmp
  version: "5.1.2"

source:
  fn: gmp-5.1.2.tar.bz2
  url: http://ftp.gnu.org/gnu/gmp/gmp-5.1.2.tar.bz2

build:
  number: 0

about:
  home: http://gmplib.org/
  license: GPLv3
  summary: GMP is a free library for arbitrary precision arithmetic, operating on signed integers, rational numbers, and floating-point numbers.
