package:
  name: r
  version: 3.1.0

source:
  fn: R-3.1.1.tar.gz
  url: http://cran.rstudio.com/src/base/R-3/R-3.1.1.tar.gz

requirements:
  build:
    - tk
  run:
    - tk

test:
  commands:
    - R -h
    - R --version
    - Rscript --version

about:
  home: http://www.r-project.org/
  license: GPL
