package:
  name: zlib
  version: "1.2.8"

source:
  fn: zlib-1.2.8.tar.gz
  url: http://zlib.net/zlib-1.2.8.tar.gz

requirements:
  build:
  
  run:
  

test:

about:
  home: http://www.zlib.net
  license: zlib
  summary: A Massively Spiffy Yet Delicately Unobtrusive Compression Library (Also Free, Not to Mention Unencumbered by Patents)
